# netlify.toml
[build]
  command = "# no build command needed"
  functions = "netlify/functions"
  publish = "frontend"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "frontend"
  functions = "netlify/functions"
  autoLaunch = true